const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.ScriptsInEvents.GlobalEs_Event18_Act1,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.int,
		C3.ScriptsInEvents.GlobalEs_Event21_Act4,
		C3.Plugins.Text.Acts.SetVisible,
		C3.ScriptsInEvents.LoadingEs_Event1_Act6
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Lantai: 0},
	{Platform: 0},
	{Bullet: 0},
	{PLAYER: 0},
	{Cone: 0},
	{FINISH: 0},
	{JUMP: 0},
	{UIGAMEOVER: 0},
	{Mouse: 0},
	{start: 0},
	{next: 0},
	{Hearts: 0},
	{Resume: 0},
	{Stop: 0},
	{CLICKRESUME: 0},
	{LEVEL: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{REM: 0},
	{JUMPBUTTON: 0},
	{Touch: 0},
	{TIMETEXT: 0},
	{Sprite11: 0},
	{Sprite13: 0},
	{GameOvertext: 0},
	{PlayAgainText: 0},
	{PABUTTON: 0},
	{POINTTEXT: 0},
	{Pin: 0},
	{Body: 0},
	{Head: 0},
	{Bottom: 0},
	{Physics: 0},
	{Skate: 0},
	{TiledBackground: 0},
	{AJAX: 0},
	{Browser: 0},
	{Sprite4: 0},
	{kotakPlayAgain: 0},
	{textPlayAgain: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{GAMEOVER: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite3: 0},
	{Sprite23: 0},
	{playButton: 0},
	{BACKTOMENU: 0},
	{Audio: 0},
	{NumberSprite: 0},
	{Sprite24: 0},
	{Sprite16: 0},
	{Sprite25: 0},
	{BG2: 0},
	{InvalidButton: 0},
	{InvalidText: 0},
	{Shoes: 0},
	{Obstacle: 0},
	{PlayerFam: 0},
	{mobil: 0},
	{lives: 0},
	{points: 0},
	{timeWatch: 0},
	{timewatchRunning: 0},
	{currentLevel: 0},
	{selectedHead: 0},
	{selectedBody: 0},
	{selectedBottom: 0},
	{selectedShoes: 0},
	{startDatetime: 0},
	{endDatetime: 0},
	{percentage: 0},
	{countdown: 0},
	{IsTokenValid: 0},
	{TokenPayload: 0},
	{Token: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Lantai: class extends self.ITiledBackgroundInstance {},
	PLAYER: class extends self.ISpriteInstance {},
	Cone: class extends self.ISpriteInstance {},
	FINISH: class extends self.ISpriteInstance {},
	JUMP: class extends self.ISpriteInstance {},
	UIGAMEOVER: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	Hearts: class extends self.ISpriteInstance {},
	Resume: class extends self.ISpriteInstance {},
	Stop: class extends self.ISpriteInstance {},
	CLICKRESUME: class extends self.ITextInstance {},
	LEVEL: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	REM: class extends self.ISpriteInstance {},
	JUMPBUTTON: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TIMETEXT: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	GameOvertext: class extends self.ITextInstance {},
	PlayAgainText: class extends self.ITextInstance {},
	PABUTTON: class extends self.ISpriteInstance {},
	POINTTEXT: class extends self.ITextInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	Bottom: class extends self.ISpriteInstance {},
	Skate: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	kotakPlayAgain: class extends self.ISpriteInstance {},
	textPlayAgain: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	GAMEOVER: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	playButton: class extends self.ISpriteInstance {},
	BACKTOMENU: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	NumberSprite: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	InvalidButton: class extends self.ISpriteInstance {},
	InvalidText: class extends self.ITextInstance {},
	Shoes: class extends self.ISpriteInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	PlayerFam: class extends self.ISpriteInstance {},
	mobil: class extends self.ISpriteInstance {}
}